const projects = [
  {
    id: 'farnsworth-house',
    title: 'Edith Farnsworth House',
    cover: 'assets/images/Edith Farnsworth House/CHICAGO.jpg',
    images: [
      'assets/images/Edith Farnsworth House/CHICAGO.jpg',
      'assets/images/Edith Farnsworth House/CHICAGO-1.jpg',
      'assets/images/Edith Farnsworth House/CHICAGO-2.jpg',
    ],
    category: 'facade',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Architect',     value: 'Ludwig Mies van der Rohe' },
      { label: 'Opened',        value: '1951' },
    ],
    description: 'I recreated this project by taking inspiration from the original design and modeling it again in a 3D software. After completing the work, I made the final renders and post-production edits. This project received an Architectural Visualization and Photoshop award achievement from the Behance team.\n\nFor this project, I used Autodesk 3ds Max, Corona Renderer, and Adobe Photoshop. The 3D modeling and visualization work were completely created by me.',
  },
  {
    id: 'riviera',
    title: 'Riviera',
    cover: 'assets/images/RIVIERA/SEA-BREEZE-RIVIERA-3.jpg',
    images: [
      'assets/images/RIVIERA/SEA-BREEZE-RIVIERA.jpg',
      'assets/images/RIVIERA/SEA-BREEZE-RIVIERA-2.jpg',
      'assets/images/RIVIERA/SEA-BREEZE-RIVIERA-3.jpg',
    ],
    category: 'facade',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Design Team',   value: 'Sea Breeze' },
      { label: 'Status',        value: 'Unbuilt' },
    ],
    description: 'The Riviera project is a residential complex where families can live in comfort and peace. The project includes two large swimming pools and features futuristic landscape design. The design was carried out by the Sea Breeze team, while the architectural design and visualization were done by Lachin Guluyev. Travertine material was used on the facade.\n\nThe complex is located in an area with a beautiful landscape and sea view. It consists of three buildings. Although its current status is "unbuilt," construction is planned in the near future.',
  },
  {
    id: 'sea-breeze-villa',
    title: 'Sea Breeze Villa',
    cover: 'assets/images/SEA BREEZE VILLA/1-SB-VILLA.jpg',
    images: [
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-1.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-2.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-3.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-4.jpg',
    ],
    category: 'interiors',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',          value: '2025' },
    ],
    description: 'The Sea Breeze Villa project is one of the most important projects for me. In this project, we used luxury and modern design elements together. The villa has a beautiful location, and we were also able to create a very elegant interior design.\n\nDuring the interior design process, we used wooden elements, shiny marble materials, luxury wallpapers, and many other details that made the interior more attractive and stylish. The interior design and 3D visualization of this project belong to the Lachin Guluyev team.',
  },
  {
    id: 'dream-land-interior',
    title: 'Dream Land Interior',
    cover: 'assets/images/Dream Land/Dream-Land-Interior.jpg',
    images: [
      'assets/images/Dream Land/Dream-Land-Interior.jpg',
      'assets/images/Dream Land/Dream-Land-Interior-2.jpg',
      'assets/images/Dream Land/Dream-Land-Interior-3.jpg',
      'assets/images/Dream Land/Dream-Land-Interior-4..jpg',
      'assets/images/Dream Land/Dream-Land-Interior-5.jpg',
    ],
    category: 'interiors',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',          value: '2024' },
    ],
    description: 'Dream Land is an apartment designed in a fully modern and minimalist style. As the name suggests, it represents the interior of our dreams — full of peace, comfort, soft colors, and gentle lighting.\n\nEveryone would want to live in a calm and relaxing place like this. The design was created according to the client\'s taste and preferences. The interior design and 3D visualization of this project belong to Lachin Guluyev.',
  },
  {
    id: 'knightsbridge-residence',
    title: 'Knightsbridge Residence',
    cover: 'assets/images/Knightsbridge Residence/Knightsbridge1.jpg',
    hero:  'assets/images/Knightsbridge Residence/FON.jpg',
    images: [
      'assets/images/Knightsbridge Residence/Knightsbridge1.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge2.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge3.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge4.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge5.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge6.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge7.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge8.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge9.jpg',
    ],
    category: 'interiors',
    meta: [
      { label: 'Design',        value: 'Lachin Guluyev' },
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',          value: '2024' },
    ],
    description: 'The Knightsbridge project is one of the most luxurious residential buildings located in the White City area of Baku. The client\'s apartment has an area of 70 square meters. The client wanted a simple and modern design from us.\n\nWe created a clean and modern interior, but at the same time, we wanted it to be different from other simple modern projects. The design and overall atmosphere of the apartment impressed me a lot. One of the most important features is that all the windows are floor-to-ceiling and open to a beautiful view. The apartment also receives a lot of natural light, which is very important.\n\nThe design and 3D visualization of this project belong to Lachin Guluyev.',
  },
];
