const projects = [
  {
    id: 'interactive-application',
    title: 'Interactive Application',
    cover: 'assets/images/Interactive App/Digital-Twin-Presentation.jpg',
    hero:  'assets/images/Interactive App/Ipad-Interactive.jpg',
    images: [
      'assets/images/Interactive App/REALTIME1.jpg',
      'assets/images/Interactive App/REALTIME2.jpg',
      'assets/images/Interactive App/REALTIME3.jpg',
    ],
    category: 'interactive',
    meta: [
      { label: 'Designer & Developer', value: 'Lachin Guluyev' },
      { label: 'Year',                 value: '2026' },
      { label: 'Software',             value: 'Unreal Engine, JavaScript, 3ds Max, Corona Renderer, Photoshop' },
    ],
    description: 'This is my 3D Interactive Application built in Unreal Engine — designed not just to visualize architecture, but to experience it. 🎮\n\nFrom a single interface, you can:\n🚁 Switch to drone view\n🧍 Walk through the environment as a human\n🏠 Explore interiors\n🧭 Navigate surroundings in real time\n\nThis project simulates a complete living ecosystem:\n🏙️ Smart surroundings & amenities system\n🏠 Fully designed residential buildings & interiors\n🚗 Animated traffic bringing life to the streets\n🧍 MetaHuman walkaround experience\n🚁 Seamless drone ↔ ground view transition\n🌦️ Ultra Dynamic Sky with 4 seasons & time-of-day\n🏫 Schools, playgrounds, sports areas\n⚡ EV charging stations\n🏗️ Active construction zone\n\nThis is not just a render. This is a new way to present architecture — interactive, dynamic, and alive. 🚀\n\n🎯 And this is only the beginning.',
    youtube: 'https://youtu.be/pf0lx6K9D1w?si=LzozJg0WefVlCCHx',
  },
  {
    id: 'riviera',
    title: 'Riviera',
    cover: 'assets/images/RIVIERA/SEA-BREEZE-RIVIERA-3.jpg',
    images: [
      'assets/images/RIVIERA/SEA-BREEZE-RIVIERA.jpg',
      'assets/images/RIVIERA/SEA-BREEZE-RIVIERA-2.jpg',
      'assets/images/RIVIERA/SEA-BREEZE-RIVIERA-3.jpg',
    ],
    category: 'facade',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Design Team',   value: 'Sea Breeze' },
      { label: 'Status',        value: 'Unbuilt' },
    ],
    description: 'The Riviera project is a residential complex where families can live in comfort and peace. The project includes two large swimming pools and features futuristic landscape design. The design was carried out by the Sea Breeze team, while the architectural design and visualization were done by Lachin Guluyev. Travertine material was used on the facade.\n\nThe complex is located in an area with a beautiful landscape and sea view. It consists of three buildings. Although its current status is "unbuilt," construction is planned in the near future.',
  },
  {
    id: 'swiss-archviz',
    title: 'Swiss Archviz',
    cover: 'assets/images/Swiss Archviz/Camera-1web.jpg',
    noHero: true,
    sideVideo: 'assets/videos/Swiss Arcviz.webm',
    images: [
      'assets/images/Swiss Archviz/Camera-1web.jpg',
      'assets/images/Swiss Archviz/Camera-2web.jpg',
      'assets/images/Swiss Archviz/Camera-3web.jpg',
    ],
    category: 'facade',
    meta: [
      { label: '3D Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',             value: '2026' },
      { label: 'Software',         value: '3ds Max, Corona Renderer, Photoshop, ComfyUI' },
    ],
    description: 'Modern Residential Visualization | Exterior Concept in Switzerland\n\nThis project reflects a balance between modern architecture and a calm, livable environment. Clean geometry, soft tones, and natural surroundings were combined to create a space that feels both elegant and comfortable.\n\nMy role in this project focused on bringing the design to life through visual storytelling:\n– 3D Visualization & Rendering\n– Lighting Setup & Atmosphere\n– Material Creation & Detailing\n– Corona Renderer Workflow\n– ComfyUI-assisted visual enhancement\n– Strong focus on realism and composition\n\nThe goal was not just to show a building, but to create a feeling — a place where people can imagine their daily life.\n\nIf you\'re looking to present your projects with high-end visuals that support sales and marketing, feel free to connect.',
  },
  {
    id: 'sea-breeze-villa',
    title: 'Sea Breeze Villa',
    cover: 'assets/images/SEA BREEZE VILLA/1-SB-VILLA.jpg',
    images: [
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-1.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-2.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-3.jpg',
      'assets/images/SEA BREEZE VILLA/1-SB-VILLA-4.jpg',
    ],
    category: 'interiors',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',          value: '2025' },
    ],
    description: 'The Sea Breeze Villa project is one of the most important projects for me. In this project, we used luxury and modern design elements together. The villa has a beautiful location, and we were also able to create a very elegant interior design.\n\nDuring the interior design process, we used wooden elements, shiny marble materials, luxury wallpapers, and many other details that made the interior more attractive and stylish. The interior design and 3D visualization of this project belong to the Lachin Guluyev team.',
  },
  {
    id: 'farnsworth-house',
    title: 'Edith Farnsworth House',
    cover: 'assets/images/Edith Farnsworth House/CHICAGO.jpg',
    images: [
      'assets/images/Edith Farnsworth House/CHICAGO.jpg',
      'assets/images/Edith Farnsworth House/CHICAGO-1.jpg',
      'assets/images/Edith Farnsworth House/CHICAGO-2.jpg',
    ],
    category: 'facade',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Architect',     value: 'Ludwig Mies van der Rohe' },
      { label: 'Opened',        value: '1951' },
    ],
    description: 'I recreated this project by taking inspiration from the original design and modeling it again in a 3D software. After completing the work, I made the final renders and post-production edits. This project received an Architectural Visualization and Photoshop award achievement from the Behance team.\n\nFor this project, I used Autodesk 3ds Max, Corona Renderer, and Adobe Photoshop. The 3D modeling and visualization work were completely created by me.',
  },
  {
    id: 'santafe-2025',
    title: 'Hyundai Santa Fe 2025 CGI',
    cover: 'assets/images/Hyundai SantaFe/SANTA-FE-fon.jpg',
    noHero: true,
    sideVideo: 'assets/videos/Santafe-animation.webm',
    images: [
      'assets/images/Hyundai SantaFe/SANTA-FE.jpg',
      'assets/images/Hyundai SantaFe/SANTA-FE-1.jpg',
      'assets/images/Hyundai SantaFe/SANTA-FE-2.jpg',
      'assets/images/Hyundai SantaFe/SANTA-FE-3.jpg',
      'assets/images/Hyundai SantaFe/SANTA-FE-4.jpg',
    ],
    category: 'products',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',          value: '2025' },
      { label: 'Software',      value: '3ds Max, Corona Renderer, Photoshop' },
    ],
    description: 'The fifth-generation Santa Fe was announced by Hyundai on 17 July 2023, followed by a full unveiling on 10 August 2023. The 2024 Hyundai Santa Fe is a bold reinvention of the popular midsize SUV, combining rugged capability with refined comfort.\n\nWith its boxier silhouette and extended wheelbase, it offers a more adventurous and spacious experience for modern families. Inside, the Santa Fe features a minimalist yet premium cabin, focused on usability and tech integration. From its wide digital displays to its panoramic sunroof, every detail enhances both driver and passenger comfort.\n\nDesigned to handle both urban roads and off-road trails, the Santa Fe balances versatility with style. Its hybrid powertrain option ensures greater fuel efficiency without compromising performance. A true midsize SUV, the 2024 Santa Fe is built for those who demand both function and flair.\n\nDeveloped under the codename MX5, Hyundai designed the vehicle to appeal to the growing outdoor lifestyle globally by adopting a boxy design. Available powertrain options include a 2.5-litre petrol, 2.5-litre turbocharged petrol, 1.6-litre turbocharged hybrid and 1.6-litre turbocharged plug-in hybrid.',
  },
  {
    id: 'dream-land-interior',
    title: 'Dream Land Interior',
    cover: 'assets/images/Dream Land/Dream-Land-Interior.jpg',
    images: [
      'assets/images/Dream Land/Dream-Land-Interior.jpg',
      'assets/images/Dream Land/Dream-Land-Interior-2.jpg',
      'assets/images/Dream Land/Dream-Land-Interior-3.jpg',
      'assets/images/Dream Land/Dream-Land-Interior-4..jpg',
      'assets/images/Dream Land/Dream-Land-Interior-5.jpg',
    ],
    category: 'interiors',
    meta: [
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',          value: '2024' },
    ],
    description: 'Dream Land is an apartment designed in a fully modern and minimalist style. As the name suggests, it represents the interior of our dreams — full of peace, comfort, soft colors, and gentle lighting.\n\nEveryone would want to live in a calm and relaxing place like this. The design was created according to the client\'s taste and preferences. The interior design and 3D visualization of this project belong to Lachin Guluyev.',
  },
  {
    id: 'knightsbridge-residence',
    title: 'Knightsbridge Residence',
    cover: 'assets/images/Knightsbridge Residence/Knightsbridge1.jpg',
    hero:  'assets/images/Knightsbridge Residence/FON.jpg',
    images: [
      'assets/images/Knightsbridge Residence/Knightsbridge1.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge2.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge3.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge4.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge5.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge6.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge7.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge8.jpg',
      'assets/images/Knightsbridge Residence/Knightsbridge9.jpg',
    ],
    category: 'interiors',
    meta: [
      { label: 'Design',        value: 'Lachin Guluyev' },
      { label: 'Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',          value: '2024' },
    ],
    description: 'The Knightsbridge project is one of the most luxurious residential buildings located in the White City area of Baku. The client\'s apartment has an area of 70 square meters. The client wanted a simple and modern design from us.\n\nWe created a clean and modern interior, but at the same time, we wanted it to be different from other simple modern projects. The design and overall atmosphere of the apartment impressed me a lot. One of the most important features is that all the windows are floor-to-ceiling and open to a beautiful view. The apartment also receives a lot of natural light, which is very important.\n\nThe design and 3D visualization of this project belong to Lachin Guluyev.',
  },
  {
    id: 'sumgayit-apartment',
    title: 'Sumgayit Apartment 60 sqm CGI',
    cover: 'assets/images/Sumgayit 60kv apt/sumgayit-apt-5.jpg',
    hero:  'assets/images/Sumgayit 60kv apt/project---in-top-photo.jpg',
    images: [
      'assets/images/Sumgayit 60kv apt/Sumgayit-apt-1.jpg',
      'assets/images/Sumgayit 60kv apt/Sumgayit-apt-2.jpg',
      'assets/images/Sumgayit 60kv apt/Sumgayit-apt-3.jpg',
      'assets/images/Sumgayit 60kv apt/Sumgayit-apt-4.jpg',
      'assets/images/Sumgayit 60kv apt/sumgayit-apt-5.jpg',
      'assets/images/Sumgayit 60kv apt/sumgayit-apt-6.jpg',
      'assets/images/Sumgayit 60kv apt/sumgayit-apt-7.jpg',
      'assets/images/Sumgayit 60kv apt/sumgayit-apt-8.jpg',
      'assets/images/Sumgayit 60kv apt/sumgayit-apt-9.jpg',
    ],
    category: 'interiors',
    meta: [
      { label: 'Designer & Visualization', value: 'Lachin Guluyev' },
      { label: 'Year',                     value: '2025' },
      { label: 'Area',                     value: '60 sqm' },
    ],
    description: 'Sumgait | 60 sqm Apartment Design\n\nThis 60 sqm apartment was designed for a young family who recently purchased their new home. Their main request was clear: create a modern living space with maximum functionality, plenty of storage solutions, and a clean aesthetic atmosphere.\n\nIn this project, I focused on soft lighting, bright tones, and custom-designed cabinets to make the apartment feel both spacious and practical. Every area was planned carefully to balance comfort, storage, and visual harmony.\n\nThe interior design and 3D visualization were created by Lachin Guluyev.\n\nI would also like to mention that the real photographs after construction are available on the main page. The images shared here are CGI visualizations, while the "built" section shows the final completed result of the project.\n\nFor me, successful interior design and visualization should always balance three important elements:\n• Aesthetics\n• Functionality\n• Budget-friendly solutions\n\nThis apartment is a good example of how a compact 60 sqm space can still feel elegant, highly functional, and financially practical at the same time.\n\nThank you for watching.',
  },
  {
    id: 'sumgayit-built',
    title: 'Sumgayit Apartment — Built',
    cover: 'assets/images/Sumgayit apartment - Built/3.jpg',
    hero:  'assets/images/Sumgayit apartment - Built/Project-fon.jpg',
    images: [
      'assets/images/Sumgayit apartment - Built/2.jpg',
      'assets/images/Sumgayit apartment - Built/3.jpg',
      'assets/images/Sumgayit apartment - Built/4.jpg',
      'assets/images/Sumgayit apartment - Built/5.jpg',
      'assets/images/Sumgayit apartment - Built/6.jpg',
      'assets/images/Sumgayit apartment - Built/7.jpg',
      'assets/images/Sumgayit apartment - Built/8.jpg',
      'assets/images/Sumgayit apartment - Built/9.jpg',
      'assets/images/Sumgayit apartment - Built/10.jpg',
    ],
    category: 'construction',
    meta: [
      { label: 'Interior Designer', value: 'Lachin Guluyev' },
      { label: 'Location',          value: 'Azerbaijan, Sumgayit' },
      { label: 'Year',              value: '2025–2026' },
      { label: 'Status',            value: 'Built' },
    ],
    description: 'I am presenting the interior design of a 60 square meter apartment located in Sumgait. I have previously shared the render images of this project on my Behance portfolio.\n\nThe apartment was designed specifically for investment purposes, with a focus on comfort, aesthetics, and budget efficiency. Light tones, wooden elements, and a welcoming entrance with LED portal lighting were used throughout the space.\n\nThe apartment consists of one bedroom, a living room, and a kitchen. Wooden materials were mainly used in the kitchen area to create a warm and natural atmosphere.\n\nFor more details, you can explore our work on our Instagram page. There, I share the renovation process, design stages, and 3D visualizations.',
  },
];
